version: 2.1

jobs:
  build-plugin:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Setup pongo
          command: |
            echo "======= setup pongo"
            apt-get update && apt-get install -y git
            git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
            chmod 777 ../kong-pongo/pongo.sh
      - run:
          name: Lint
          command: |
            echo "====== run lint in code"
            ../kong-pongo/pongo.sh lint
      - run:
          name: Build
          command: |
            echo "======= build plugin"
            ../kong-pongo/pongo.sh build
      - run:
          name: Tests
          command: |
            echo "======= running tests with coverage"
            mkdir test-results/
            export POSTGRES_IMAGE=postgres:15
            export KONG_VERSION=2.8.4
            export KONG_LOG_LEVEL=debug
            ../kong-pongo/pongo.sh up
            sleep 5
            ../kong-pongo/pongo.sh run -- --coverage >> test-results/output.xml 2>&1 || true
            echo "======= sanitizing output tests"
            end_line=$(grep -no "<testsuites" test-results/output.xml | cut -d: -f1)
            end_line=$(echo $end_line | bc)
            end_line=$((end_line - 1))
            sed -i "1,${end_line}d" test-results/output.xml
            grep "errors='0'" test-results/output.xml
            if [ $? -ne 0 ]; then
                exit 1
            fi
            grep "failures='0'" test-results/output.xml
            c=$?
            if [ $c -ne 0 ]; then
                echo "saiu no erro"
                exit 1
            fi
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results/output.xml
          destination: junit.xml
      - store_artifacts:
          path: ./luacov.report.out
          destination: luacov.report.out
      - store_artifacts:
          path: ./luacov.stats.out
          destination: luacov.stats.out
  deploy-plugin:
    docker:
      - image: cimg/base:2022.09
    steps:
      - run:
          name: Setup luarocks
          command: |
            sudo apt-get update && sudo apt-get install luarocks -f
            luarocks install lua-cjson --local
      - checkout
      - run:
          name: Publish
          command: |
            echo "====== publish plugin version ${CIRCLE_TAG}"
            sed -i "s|\${TAG}|${CIRCLE_TAG}|g" kong-plugin-request-rules-validate-1.rockspec
            mv kong-plugin-rules-validate-TAG-1.rockspec kong-plugin-rules-validate-${CIRCLE_TAG}-1.rockspec
            luarocks upload --api-key ${LUAROCKS_KEY} kong-plugin-rules-validate-${CIRCLE_TAG}-1.rockspec
workflows:
  version: 2
  build:
    jobs:
      - build-plugin:
          filters:
            branches:
              only: /.*/
      - deploy-plugin:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
